### ISSUE TITLE
Your cmake file not work

### ISSUE THREAD

**Issue by LionZXY** [alex85k/sqlite3-cmake#1]
I try add this project int my repo, but it not comping.
My CMakeLists.txt (adding libraries):
```
PROJECT(sqlite3)
cmake_minimum_required(VERSION 2.8)

link_libraries(pthread)
link_libraries(dl)

include_directories(${CMAKE_CURRENT_SOURCE_DIR})
add_library(sqlite3 STATIC src/sqlite3.c src/sqlite3.h src/sqlite3ext.h)
add_executable(sqlite src/sqlite3.c src/shell.c src/sqlite3.h src/sqlite3ext.h)
set_target_properties(sqlite PROPERTIES OUTPUT_NAME sqlite3)

add_definitions(-DSQLITE_ENABLE_RTREE)
add_definitions(-DSQLITE_ENABLE_FTS4)
add_definitions(-DSQLITE_ENABLE_FTS5)
add_definitions(-DSQLITE_ENABLE_JSON1)

target_link_libraries(sqlite3 ${CMAKE_DL_LIBS})
install(FILES src/sqlite3.h src/sqlite3ext.h DESTINATION include)
install(TARGETS sqlite3 LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)
install(TARGETS sqlite RUNTIME DESTINATION bin)
```

My docker file:
```
FROM ubuntu:latest

RUN apt-get -qq update && apt-get -qq upgrade && apt-get -qqy install g++ libboost-all-dev cmake cmake-data libc6 libc6-dev sqlite3

WORKDIR /tmp/recast
RUN rm -rf /tmp/recast/*
COPY libs libs
COPY src src
COPY CMakeLists.txt ./

RUN mkdir build && cd build && cmake .. && make
```
And crash:

> CMakeFiles/sqlite.dir/src/sqlite3.c.o: In function `fts5Bm25GetData':
> /home/lionzxy/Recast/libs/sqlite/src/sqlite3.c:184444: undefined reference to `log'
> collect2: error: ld returned 1 exit status
> libs/sqlite/CMakeFiles/sqlite.dir/build.make:120: recipe for target 'libs/sqlite/sqlite3' failed
> make[2]: *** [libs/sqlite/sqlite3] Error 1
> CMakeFiles/Makefile2:145: recipe for target 'libs/sqlite/CMakeFiles/sqlite.dir/all' failed
> make[1]: *** [libs/sqlite/CMakeFiles/sqlite.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 33%] Linking C static library libsqlite3.a
> [ 33%] Built target sqlite3
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2

In this Pull Request i try build project with sqlite https://github.com/bender-wardrobe/Recast/pull/20

**Comment by LionZXY** [comment]
P.S. I remove 
`add_definitions(-DSQLITE_ENABLE_FTS5)`
And all work. Why?

**Comment by alex85k** [comment]
Most likely, it needs math library for computing logarithms. Seems it is used only in FTS5 part only. I'll try to add checks.

**Comment by alex85k** [comment]
On some Linux systems it is used by default so I missed it (or there was no log function in previous versions).

**Comment by alex85k** [comment]
This https://github.com/alex85k/sqlite3-cmake/commits/master should fix it (checked on Redhat 6).
Thank you for your help!
